# Generated by Django 4.0.3 on 2023-06-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilevo',
            name='manufacturer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='automobilevo',
            name='model',
            field=models.CharField(max_length=100),
        ),
    ]
