# Generated by Django 4.0.3 on 2023-06-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_automobilevo_manufacturer_alter_automobilevo_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automobilevo',
            name='model',
            field=models.CharField(default='', max_length=100),
        ),
    ]
