# Generated by Django 4.0.3 on 2023-06-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0008_alter_technician_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date_time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(default='2023-10-21'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='18:00'),
        ),
    ]
